name: CD

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download packaged extension
        uses: actions/download-artifact@v3
        with:
          name: jsfr
      - name: Publish extension
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}