name: CD

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Package
        run: mkdir -p dist && npm run package

      - name: Publish extension
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload packaged extension
        uses: actions/upload-artifact@v3
        with:
          name: jsfr
          path: dist/jsfr.vsix

    outputs:
      package-version: ${{ steps.package-version.outputs.current-version }}

  release:
    needs: [publish]
    runs-on: ubuntu-latest

    env:
      PACKAGE_VERSION: ${{ needs.publish.outputs.package-version }}
    
    steps:
      - name: Download packaged extension
        uses: actions/download-artifact@v3
        with:
          name: jsfr

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.PACKAGE_VERSION }}
          prerelease: true
          title: ${{ env.PACKAGE_VERSION }}
          files: |
            dist/jsfr.vsix
            LICENSE