name: Build (master)

on:
  push:
    branches: [ master ]

jobs:
  build-master:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: ./.github/workflows/build.yml

      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.package-version.outputs.current-version }}"
          prerelease: true
          title: "Development Build"
          files: |
            dist/jsfr.vsix
            LICENSE

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jsfr
          path: dist/jsfr.vsix