name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 16.4.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.4.1

      - name: Install dependencies
        run: npm ci

      - name: Package
        run: mkdir -p dist && npm run package

      - name: Release
        if: success() && github.event_name == 'push'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/jsfr.vsix
            LICENSE

      - name: Upload artifact
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: jsfr
          path: dist/jsfr.vsix