name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16.4.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.4.1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: xvfb-run -a npm test

      - name: Package
        run: mkdir -p dist && npm run package

      - name: Release
        if: success() && github.event_name == 'push'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/jsfr.vsix
            LICENSE

      - name: Publish
        if: success() && github.event_name == 'push'
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}